---
driver:
  name: docker
  socket: <%= ENV['DOCKER_HOST'] %>
  provision_command: curl -L https://www.opscode.com/chef/install.sh | bash

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
  - name: centos-6.4

suites:
  - name: default
    run_list:
      - recipe[route53-test]
    attributes:
      route53:
        zone_id: "yourdomain.com"
        aws_access_key_id: "keep"
        aws_secret_access_key: "secrets"
